### ISSUE TITLE
Is there a sample codebase of this in action.

### ISSUE THREAD

**Issue by pjbr** [mfdeveloper/cordova-plugin-nativeview#11]
After initializing a cordova project and adding the platform i cannot figure out how to add a new UIViewController to my ios project

**Comment by mfdeveloper** [comment]
Hello @pjbr !! Thank you for report this!

By now, there is a example project only for `Android` platform in folder [android](https://github.com/mfdeveloper/cordova-plugin-nativeview/tree/master/android). This project have been recreated today, and will be increased with more changes in the next days, because I'm using this plugin in a real project by now.

For `ios` platform, still not exists a **XCode** example project, but me and my team are working in improvements of this plugins for this platforms, like:

- Use of `[storyboard performSegue]` dinamically, 
- Run preload actions and others general changes to support many IOS projects (with or not Storyboards, ViewControllers with or not `xib's` , etc).

After finish this changes, we will push a example **XCode** project too, in one or two weeks. After that, I will add **automated tests** to simulate scenarios that this plugin respond. So please, be patient :)

Whether your project needs a "fast implementation", you can do these steps below:

### From a Cordova project

#### Use [cocoapods](https://cocoapods.org/) like IOS package manager

1 - Create a `.podspec` file for your(s) ViewController(s) that will be opened from Cordova app. You can follow the oficial guide of cocoapods: [making-a-cocoapod](https://guides.cocoapods.org/making/making-a-cocoapod.html)

2. Create a `Podfile` (maybe with a custom `npm script` that copy from your root project to `platforms/ios` folder, or something else) and add your ViewController like a dependency:

```ruby
pod 'my-custom-pod', :git => 'https://github.com/my-repo/my-custom-view-controllers.git', :branch => 'my-git-branch'
```
> **PS:** You can pass a `:path` to a relative folder with your `.podspec`, or download the dependency from http://cocoapods.org, insteaof `:git` param.

#### Or use local `ViewController(s)`

1 . Copy your custom ViewController to `platforms/ios/[generated_project]/Classes
2 . Make sure that the copied class was added to compile during XCode `Building phase`

I hope that these informations help you :smiley:

**Comment by mfdeveloper** [comment]
Hello @pjbr !

It is a soo old issue. I think that you can use this plugin correctly, right?

I'm closing this issue. If you have any trouble, please, keep me in touch 😄
