### ISSUE TITLE
Going back to Cordova from native iOS view

### ISSUE THREAD

**Issue by jakeclarklucentmobile** [mfdeveloper/cordova-plugin-nativeview#8]
Hello,
I am launching my view like this

```js
window['cordova'].plugins.NativeView.show('Storyboard', 'PAYMENT')
```

It opens my view located on my storyboard. From here, via a button push I want to exit the view and go back to the cordova webview. The MainViewController that cordova generated is NOT located on my storyboard.

I have tried running these functions in swift 3, from the PAYMENT viewcontroller, to try to close the view. None of these have worked.

```swift
self.navigationController?.dismiss(animated: false) self.navigationController?.popViewController(animated: true)
self.view.window?.rootViewController?.dismiss(animated: true, completion: nil)
```

You can see in my screenshot that I have connected a navigation controller to the story board, and set PAYMENT as its root view. Note the relationship under Presenting Segues in the right panel

I looked at the NativeView source code, and I see that if i run show again, it should close the view, but I'm not sure how to call the show function from my swift view controller.

Help would be appreciated - and keep in mind - this is my first native ios view and first time with swift and xcode. 

Thanks!

<img width="1651" alt="screen shot 2018-04-12 at 1 05 51 pm" src="https://user-images.githubusercontent.com/8260541/38695580-51ae413a-3e52-11e8-9ce6-2ed2c597495c.png">

**Comment by mfdeveloper** [comment]
Hello @jakeclarklucentmobile !! Thank you for your issue. Sorry for my late response

Your issue is similar a #7 reported by another person. Their solution was use **`popViewController(animated: true)`** and it work's well.

So, let me understand your problem better:

1. You sad that the `MainViewController` is not located into your XCode project. Why did you do this? 

2. Whether you are using the `PaymentViewController.swift` like your **rootViewController**, make sure this class share the same `NavigationController` with your Cordova WebView. In the IOS implementation of this plugin, I'm using [pushViewController()](https://github.com/mfdeveloper/cordova-plugin-nativeview/blob/master/src/ios/CDVNativeView.swift#L55) method (both Objective-C and Swift versions) from `self.viewController` (The Cordova ViewController, at this case). Otherwise, when you call `NativeView.show()`, your last view controller will be replaced and go back using `pop` WILL NOT BE POSSIBLE. In this case, you will need instantiate the Cordova ViewController again dynamically, like I did in: https://github.com/mfdeveloper/cordova-plugin-nativeview/blob/master/src/ios/CDVNativeView.swift#L66, and set again like a `rootViewController`. It's a hard way, and I don't recommend this :sweat_smile: 

3. Are you using the `Objective-C` or `Swift` version of this plugin? How did you use this plugin into your project?

**Comment by krishnaclouds** [comment]
I tried to Use the plugin to Open Ios Native View. The Storyboard I am passing in is embedded in a View Controller. But still, Since MainViewController is not embedded in Navigation Controller/ or maybe some other reason, The New View Controller is being set as RootViewController. 

Due to this, I'm unable to POP the ViewController, when I need to get back to my Cordova Activity!!

Any clue is appreciated.

**Comment by mfdeveloper** [comment]
@krishnaclouds and @jakeclarklucentmobile Do you have some `NavigationController` in your case? Did you do a `[pushViewController]` to another view before call `NativeView.show()` ?

**Comment by krishnaclouds** [comment]
Yes, I am using Embedding my ViewController in a Navigation bar. Is there anything different that is to be done?

**Comment by krishnaclouds** [comment]
I added this Code to my AppDelegate.m

    UINavigationController *aNavigationController = [[UINavigationController alloc]                                                  
    initWithRootViewController:self.viewController];
    self.navigationController = aNavigationController;
    self.window.rootViewController = self.navigationController;

Now, the code gets into the if clause if([self.viewController navigationController] != nil)
But facing with the issue -> The ViewController: <ViewControllerName> was not found

I verified that, StoryBoard is set to the same ViewController.

**Comment by krishnaclouds** [comment]
Edited my AppDelegate.m

- didFinishLaunchingWithOptions

```
    self.viewController = [[MainViewController alloc] init];
    UINavigationController *navController = [[UINavigationController alloc] initWithRootViewController:self.viewController];
    self.navigationController = navController;
    self.window.rootViewController = self.navigationController;
    return [super application:application didFinishLaunchingWithOptions:launchOptions];
```

- Create a new ViewController.xib -> 'NewViewController'

Upon calling NativeView.show('NewViewController', 'NewViewController');
The plugin executes the follwing code block!

   ```
     NSLog(@"-LOG 1- viewController navigationController is not nil");
        
        if ([self.viewController.navigationController.viewControllers count] > 1) {
            NSLog(@"-LOG 2- ViewController count is greater then 1");
            [self.viewController.navigationController popViewControllerAnimated: YES];
        }else{
            NSLog(@"-LOG 3- Trying to instancicate with className: %@", className);
            viewController = [self tryInstantiateViewWithName: className];
            NSLog(@"-LOG 4- viewController after InstantiateWithName: %@", viewController);
            [self.viewController.navigationController pushViewController:viewController animated:YES];
        }
```

The control is successfullying reaching LOG 4, but the view is not being populated!!

**Comment by mfdeveloper** [comment]
Ok @krishnaclouds, I understand by now! Tomorrow, I will create a Cordova/XCode project example with this scenario, and push to this repo, ok?

**Comment by krishnaclouds** [comment]
Hey, If I am not pushing, Have you tried creating the scenario?! @mfdeveloper

**Comment by mfdeveloper** [comment]
Hello @krishnaclouds !! I'm working for this. The `[master]` really have a bug when using Storyboards + `NavigationController`. I pushed the branch [[ios-example]](https://github.com/mfdeveloper/cordova-plugin-nativeview/tree/ios-example) with a fix...you can follow the changes in the next days.

I've created a example project, but still remains some setup changes and I don't have a time by now to finish this quicly because I'm working with another technologies at my job. So, please, be patient. If you need this fix fast, get the **ios-example** branch and try apply in your current XCode project !!

**Comment by krishnaclouds** [comment]
Hey, @mfdeveloper Thanks for all the support. A little tweak in the plugin code, helped me solve my case. 

In the case, there is no navigation controller, Instead of making the new View Controller a root view controller, I just presented it.

`[appDelegate.window.rootViewController presentViewController:viewController animated:NO completion:nil];`

And then, from the invoked class, I called on
`[self dismissViewControllerAnimated:NO completion:nil];`

**Comment by mfdeveloper** [comment]
Hello @krishnaclouds !

Can we close this issue by now? I did some improvements and merged to the branch **[master]**, and fixed the `NavigationController` problem 😄

**Comment by krishnaclouds** [comment]
Sure Please

**Comment by SibabratSwain** [comment]
@krishnaclouds Could you please help me out with similar situation. I am completely new to IOS development so I could not figure out where to add your solution. 

I have basically an ionic app I have built the ios app and added a few storyboards and swift classes to the Classes directory.
I have two Controllers, ViewController.swift and VdieoChatViewController.swift. 

I have embed navigation to these. So while I use this plugin and open the ViewController, there I open VideoChatViewController. Now at a certain function in the  VideoChatViewController I want to go back to the previous ionic screen where it has opened.

 Please help me out. 

**test.ts**
` await cordova.plugins.NativeView.show('Main', 'ViewController', 'hello-video');`

![Screen Shot 1942-05-21 at 2 54 57 PM](https://user-images.githubusercontent.com/38970037/89998951-cde3d400-dcab-11ea-8b74-0b3771fc158f.png)
![Screen Shot 1942-05-21 at 2 55 59 PM](https://user-images.githubusercontent.com/38970037/89999056-f10e8380-dcab-11ea-941e-8d261cc338c4.png)
